apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: os-deployment
  template:
    metadata:
      labels:
        app: os-deployment
    spec:
      containers:
      - name: os-deployment
        image: mowoh/os-deployment:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: os-deployment-service
spec:
  selector:
    app: os-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer